[project]
name = "fastui-lab"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Shroominic", email = "db2002dominic@gmail.com" }
]
dependencies = [
    "fastui>=0.2.0",
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0.post1",
    "click>=8.1.7",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
startapp = "fastui_lab.app:start"

[tool.rye]
managed = true
dev-dependencies = [
    "mypy>=1.7.1",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.mypy]
mypy_path = "src/"
ignore_missing_imports = true
follow_imports = "skip"
exclude = "(fastui/.*|venv/.*|dist/.*|wheels/.*|.*egg-info)"
