[project]
name = "fastui-chat"
version = "0.0.1"
description = "Minimalistic chatbot ui using fastapi, fastui and langchain."
authors = [
    { name = "Shroominic", email = "contact@shroominic.com" }
]
dependencies = [
    "fastui>=0.3.0",
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0.post1",
    "openai>=1.5.0",
    "python-multipart>=0.0.6",
    "langchain>=0.0.350",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
startapp = "fastui_chat.app:start"

[tool.rye]
managed = true
dev-dependencies = [
    "mypy>=1.7.1",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.mypy]
mypy_path = "src/"
ignore_missing_imports = true
follow_imports = "skip"
exclude = "(fastui/.*|venv/.*|dist/.*|wheels/.*|.*egg-info)"
